# This is a basic workflow that is manually triggered

name: Beta deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'Versão da release'
        required: true
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Nome para a versão'
        # Input has to be provided for the workflow to run
        required: true
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install Fastlane dependencies
      run: sudo gem install bundler && sudo gem install rake
    - name: Install Fastlane
      run: |
        bundle config path vendor/bundle
        sudo bundle update
    - name: Run yarn install
      run: yarn
    - name: Run build
      run: yarn build-release-android skip_release:true
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{github.event.inputs.tag}}
        release_name: ${{github.event.inputs.name}}
        draft: false
        prerelease: false
